#!/usr/bin/env python3
"""從 `WORRIORS.EXP` 抽出「搜尋能找到的東西」那三張表 → Go 源碼。

推導見 `docs/re/96`。三張表都在執行檔裡(不在任何資料檔),所以引擎必須內嵌 ——
與生怪表、陷阱權重表同樣的處理(`CLAUDE.md §3.0` 的素材規則管的是**美術與音樂**,
執行檔裡的數值表本來就只能抽出來寫進碼)。

    ./tools/dev.sh python3 tools/dump_hidden_items.py > internal/u5data/hiddenitems.go

⚠ 位址是 FM Towns `WORRIORS.EXP` 的**線性位址**;檔案位移 = 線性 − 0x200。
"""
import json
import struct
import sys

EXP = "re_work/fmtowns/iso/U5_E/WORRIORS.EXP"

# 113 筆固定物品的六個平行陣列(原版 `sub_14160`,基底 `dword_55A48` + 位移)
FIXED_COUNT = 0x71
A_KIND = 0x55A64  # +0x1C  種類(同時是 `sub_13CB0` 的描述索引)
A_QUAL = 0x55AD8  # +0x90  品質
A_LOC = 0x55B4C   # +0x104 地點碼
A_FLOOR = 0x55BC0 # +0x178 樓層
A_X = 0x55C34     # +0x1EC X
A_Y = 0x55CA8     # +0x260 Y

# 三個秘密採藥點(原版 `sub_14090`)
HERB_COUNT = 3
H_X, H_Y, H_KIND, H_NAME = 0x55A4C, 0x55A4F, 0x55A52, 0x55A58


def main() -> int:
    raw = open(EXP, "rb").read()

    def at(lin: int, n: int) -> bytes:
        return raw[lin + 0x200 : lin + 0x200 + n]

    def cstr(ptr: int) -> str:
        o = ptr + 0x200
        return raw[o : raw.index(b"\0", o)].decode("latin-1")

    kind = at(A_KIND, FIXED_COUNT)
    qual = at(A_QUAL, FIXED_COUNT)
    loc = at(A_LOC, FIXED_COUNT)
    flr = at(A_FLOOR, FIXED_COUNT)
    xs = at(A_X, FIXED_COUNT)
    ys = at(A_Y, FIXED_COUNT)

    hx, hy, hk = at(H_X, HERB_COUNT), at(H_Y, HERB_COUNT), at(H_KIND, HERB_COUNT)
    hn = [cstr(p) for p in struct.unpack_from(f"<{HERB_COUNT}I", raw, H_NAME + 0x200)]

    w = sys.stdout.write
    w("// Code generated by tools/dump_hidden_items.py; DO NOT EDIT.\n")
    w("// 來源:FM Towns `WORRIORS.EXP`(線性 0x55A4C / 0x55A64 起)。推導見 `docs/re/96`。\n\n")
    w("package u5data\n\n")
    w("// HiddenItem 是一筆「搜尋能找到的固定物品」(原版 `sub_14160` 的六個平行陣列)。\n")
    w("type HiddenItem struct {\n")
    w("\tKind    byte // 物件種類,**同時是** `DungeonRoomItemName` 的索引\n")
    w("\tQuality byte // 品質(數量 / 裝備編號 / 月石編號,依種類而定)\n")
    w("\tLoc     byte // 地點碼(0 = 大地圖)\n")
    w("\tFloor   byte // 樓層(0xFF = −1 = 地下世界)\n")
    w("\tX, Y    byte\n")
    w("}\n\n")
    w(f"// HiddenItemCount 是表的長度(原版 `cmp ebx, {FIXED_COUNT:#x}`)。\n")
    w(f"const HiddenItemCount = {FIXED_COUNT}\n\n")
    w("// HiddenItems 是那 113 筆。\n")
    w("var HiddenItems = [HiddenItemCount]HiddenItem{\n")
    for i in range(FIXED_COUNT):
        w(
            f"\t{{{kind[i]:#04x}, {qual[i]:#04x}, {loc[i]:#04x}, "
            f"{flr[i]:#04x}, {xs[i]:#04x}, {ys[i]:#04x}}},\n"
        )
    w("}\n\n")
    w("// HerbSpot 是一個秘密採藥點(原版 `sub_14090` 的三筆)。\n")
    w("type HerbSpot struct {\n")
    w("\tX, Y byte\n")
    w("\tHerb byte   // 藥草編號,索引進 `ReagentNames`\n")
    w("\tName string // 原版印的那個字串\n")
    w("}\n\n")
    w("// HerbSpots 是三個採藥點。★ 只在**午夜**(小時 == 0)採得到,而且**每天每點一次**。\n")
    w("var HerbSpots = [%d]HerbSpot{\n" % HERB_COUNT)
    for i in range(HERB_COUNT):
        w(f"\t{{{hx[i]:#04x}, {hy[i]:#04x}, {hk[i]:#04x}, {json.dumps(hn[i])}}},\n")
    w("}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
